GET http://localhost:3000/transaksi

###
GET http://localhost:3000/transaksi/2

###
POST http://localhost:3000/transaksi/65
content-type: application/json

{
    "count":23
}

###
DELETE http://localhost:3000/transaksi/1
