###
POST http://localhost:3000/user/register
content-type: application/json

{
    "username": "Arsat Teguh",
    "email": "arsat@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/user/login
content-type: application/json

{
    "email":"admin@gmail.com",
    "password":"123"
}

###
POST http://localhost:3000/user/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoia29uc3RhIiwiaWF0IjoxNjg5MjQwNDAyLCJleHAiOjE2ODkyNDEzMDJ9.jw0rNY2FeY5eFZ3vlt0-yBlOi-FIPOV8q8Btfz9K8XU
